// Used this to test getting all users worked correctly
# router.get('/', (req, res) => {
#     res.send('hello world!')

# })
GET http://localhost:8080/users/

###
// Testing user search works correctly
GET http://localhost:8080/users/check
###
// Testing create user works properly
POST http://localhost:8080/users
Content-Type: application/json

{
    "firstName" : "check",
    "lastName" : "check",
    "email" : "checkin",
    "password" : "check",
    "subscription" : "check"
}

###
// Testing delete works properly
DELETE http://localhost:8080/users/checkin

###
// Testing post works properly
POST http://localhost:8080/users/check
Content-Type: application/json

{
    "firstName" : "check",
    "lastName" : "check",
    "email" : "checkywecky",
    "password" : "check",
    "subscription" : "kcehc"
}