http://localhost:8080/users/get/

###
// Testing user search works correctly
http://localhost:8080/users/get/cooey/check
###
// Testing create user works properly
POST http://localhost:8080/users/create/
Content-Type: application/json

{
    "firstName" : "check",
    "lastName" : "check",
    "email" : "coo",
    "password" : "check",
    "subscription" : "check"
}

###
// Testing delete works properly
DELETE http://localhost:8080/users/coo

###
// Testing update works properly
POST http://localhost:8080/users/update/cgckgu
Content-Type: application/json

{
    "firstName" : "check",
    "lastName" : "check",
    "email" : "checkywecky",
    "password" : "check",
    "subscription" : "kcehc"
}